export const FETCH_GITHUB_USERS = 'FETCH_GITHUB_USERS';
export const FETCH_GITHUB_USERS_SUCCESS = 'FETCH_GITHUB_USERS_SUCCESS';
export const FETCH_GITHUB_USERS_FAIL = 'FETCH_GITHUB_USERS_FAIL';

export const SEARCH_USER_BY_NAME = 'SEARCH_USER_BY_NAME';
export const SEARCH_USER_BY_NAME_SUCCESS = 'SEARCH_USER_BY_NAME_SUCCESS';
export const SEARCH_USER_BY_NAME_FAIL = 'SEARCH_USER_BY_NAME_FAIL';
